// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQRdcVGiGwlaJaVo8qkBnq0slAt7PuCqM',
    appId: '1:643543836902:web:19d3ce45acd23c17ec3327',
    messagingSenderId: '643543836902',
    projectId: 'l5iot-b08c1',
    authDomain: 'l5iot-b08c1.firebaseapp.com',
    storageBucket: 'l5iot-b08c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv7Q3EDKC4_pSq5-i5NwhFSNGPDEKLnuw',
    appId: '1:643543836902:android:f6ca2aac002bf88aec3327',
    messagingSenderId: '643543836902',
    projectId: 'l5iot-b08c1',
    storageBucket: 'l5iot-b08c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJt03JgOZlO9IUGiE8FY_FNZsHcEXAWk',
    appId: '1:643543836902:ios:f5dc4e582fafcd4eec3327',
    messagingSenderId: '643543836902',
    projectId: 'l5iot-b08c1',
    storageBucket: 'l5iot-b08c1.appspot.com',
    iosClientId: '643543836902-gg81vmjtk6287ua434qci9o7nl2qlrdq.apps.googleusercontent.com',
    iosBundleId: 'ro.upb.iot5',
  );
}
